name: Monthly EIA Data Update

on:
  schedule:
    - cron: '0 0 1 * *'  # Run at 00:00 on the 1st of every month (UTC)
  workflow_dispatch:     # Also allow manual trigger from GitHub UI

jobs:
  fetch-and-process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run data fetch script
        env:
          EIA_API_KEY: ${{ secrets.EIA_API_KEY }}
        run: |
          python scripts/fetch_eia_data.py
